routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//Pengiriman
Route::resource('/pengiriman', 'PengirimanController');
Route::post('/pengirimandelete', 'PengirimanController@deletelistpengiriman')->name('pengiriman.deletelistpengiriman');

//PackingList
Route::resource('/packinglist', 'PackingListController');
Route::post('/cetak_pdf','PackingListController@cetak_pdf')->name('packinglist.cetak_pdf');
Route::post('/detailpengirimankapal', 'PackingListController@showdetailpengirimankapal')->name('packing.showdetailpengirimankapal');
Route::post('/packingapproval', 'PackingListController@approval')->name('packing.approval');
Route::post('/fillsealshow', 'PackingListController@fillsealshow')->name('packing.fillsealshow');
Route::post('/submitfillseal', 'PackingListController@submitfillseal')->name('packing.submitfillseal');


//StatusPengiriman
Route::resource('/statuspengiriman', 'StatusPengirimanController');
Route::post('/historipengiriman', 'StatusPengirimanController@showhistoripengiriman')->name('statuspengiriman.showhistoripengiriman');
Route::post('/historicomplete', 'StatusPengirimanController@showcomplete')->name('statuspengiriman.showcomplete');
Route::post('/statuscomplete', 'StatusPengirimanController@statuscomplete')->name('statuspengiriman.statuscomplete');


//klaim
Route::resource('/klaim', 'KlaimPengirimanController');
Route::post('/uploadbrgrusak', 'KlaimPengirimanController@uploadphotoandupdate')->name('klaimpengiriman.uploadphotoandupdate');
Route::post('/uploadkettgl', 'KlaimPengirimanController@uploadketerangantgl')->name('klaimpengiriman.uploadketerangantgl');
Route::post('/updatestatusklaim', 'KlaimPengirimanController@updatestatusklaim')->name('klaim.updatestatusklaim');



//Document
Route::resource('/document', 'DocumentController');


//logout
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

//login
Route::get('loginnew', '\App\Http\Controllers\Auth\LoginController@loginnew')->name('login.loginnew');

//register
route::get("registernew",'\App\Http\Controllers\Auth\RegisterController@registernew')->name('register.registernew');

resources/views/document.blade.php
@extends('layouts.layout')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Document
        <!-- <small>Control panel</small> -->
      </h1>
         <ol class="breadcrumb">
        <li><a href="{{route('home')}}"><i class="fa fa-home"></i>Home</a></li>
        <li class="active">Document</li>
      </ol>
      <section class ="content">
      </section>
   </section>
  </div>
@endsection
@section('script')

<script type="text/javascript"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.layout')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Home
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#">welcome</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="box">
   

        <!-- Jabatan -->
        <div class="box-body">
          <div class="col-lg-6 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>Pengiriman</h3>

              <p>Menu Pengiriman</p>
            </div>
            <div class="icon">
              <i class="fa fa-send"></i>
            </div>
            <a href="{{route('pengiriman.index')}}" class="small-box-footer">Click Here <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-6 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
               <h3>Packing List</h3>

              <p>Menu Packing List</p>
            </div>
            <div class="icon">
              <i class="fa fa-cube"></i>
            </div>
            <a href="{{route('packinglist.index')}}" class="small-box-footer">Click Here <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>

          <div class="col-lg-6 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>Status Pengiriman</h3>

              <p>Menu Status Pengiriman</p>
            </div>
            <div class="icon">
              <i class="fa fa-check"></i>
            </div>
            <a href="{{route('statuspengiriman.index')}}" class="small-box-footer">Click Here <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
       <!--  <div class="col-lg-6 col-xs-6">
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>Document</h3>

              <p>Menu Document</p>
            </div>
            <div class="icon">
              <i class="fa fa-sticky-note-o"></i>
            </div>
            <a href="{{route('document.index')}}" class="small-box-footer">Click Here <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div> -->

          <div class="col-lg-6 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>Klaim</h3>

              <p>Menu Klaim Barang</p>
            </div>
            <div class="icon">
              <i class="fa  fa-exclamation"></i>
            </div>
            <a href="{{route('klaim.index')}}" class="small-box-footer">Click Here <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>


        </div>



        <!-- /.box-body -->
       <!--  <div class="box-footer">
         <button type="button" class="btn btn-success">Submit</button>
        </div> -->

        <!-- /.box-footer-->
      <!-- tempat div -->
      <!-- /.box -->

    </section>

 </div>

@endsection

resources/views/loginnew.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Teru Tritunggal | Log in</title>
 <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{{asset('plugins/iCheck/all.css')}}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a><b>Teru</b>Tritunggal</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form method="POST" action="{{ route('login') }}">
      @csrf 
      <div class="form-group has-feedback">
        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" placeholder ="E-mail" autofocus> 
          @error('email')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>


      <div class="form-group has-feedback">
         <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password" placeholder="Password">
          @error('password')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>


      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <a href="{{route('register.registernew')}}" class="text-center">Register a new membership</a>
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">{{ __('Login') }}</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <!-- /.social-auth-links -->

<!--     <a href="#">I forgot my password</a><br> -->
    

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


<!-- jQuery 3 -->
<script src="{{asset('bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- iCheck -->
<script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

resources/views/packing_pdf.blade.php
<!DOCTYPE html>
<html>

<head>
  <title>PDF Kapal</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style type="text/css">
  .page_break{page-break-before:always;}

  #footer {
      position: fixed;
      right: 0px;
      bottom: 10px;
      text-align: center;
      border-top: 1px solid black;
    }

  #footer .page:after{
    content: counter{page,decimal};
  }

  @page {
      margin: 20px 30px 40px 50px;
    }
</style>
</head>
<body>
  <style type="text/css">
    table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  width: 100%;
}
  </style>
  <center>
   <?php $d=$tableprint[0];?>
   <h4>DAFTAR ISI KAPAL <?php echo $d->kapal ?></h4>
    <h6><a target="_blank" href="">KEBERANGKATAN : <?php echo $d->kota_pengirim ?>, TUJUAN <?php echo $d->kota_penerima ?>, TRIP : <?php echo $d->tgl_pengiriman  ?></a></h5>
  </center>
  <div>
  <table>
    <thead>
      <tr>
        <th>Nama Container</th>
        <th>Nama Penerima</th>
        <th>Barang</th>
        <th>Qty Barang</th>
        <th>Total Kubikasi</th>
      </tr>
    </thead>
    <tbody>
        <?php
         $index =0;
         $totalkubikasiseluruhnya = 0;
         $totalqtybarang=0;
         foreach($tableprint as $d=>$data)
                    {
                      $idpengirimanutkrowspan = $tableprint->where('idpengiriman',$data->idpengiriman)->count();
                       $index+=1;
                      ?>
                        <tr>
                          <?php if($index==1) { ?>
                             <td rowspan="{{$idpengirimanutkrowspan}}">
                              <?php
                                echo $data->nama_container." / ".$data->seal;
                              ?>
                            </td>
                            <?php } ?>
                            
                          <?php if($index==1){ ?>
                            <td rowspan="{{$idpengirimanutkrowspan}}">
                              <?php
                                echo $data->nama_penerima;
                              ?>
                            </td>
                            <?php } ?>
                            <td>
                              <?php
                                echo $data->nama_barang;
                              ?>
                            </td>
                            <td>
                              <?php 
                            	echo $data->qty_barang;
                            	$totalqtybarang+=$data->qty_barang;
                              ?>
                            </td>
                            <td>
                              <?php
                                echo $data->total_kubikasi;
                                $totalkubikasiseluruhnya+=$data->total_kubikasi;
                              ?>
                            </td>
                           </tr>
                        <?php 
                        if ($index==$idpengirimanutkrowspan) 
                        { 
                        	$index=0;
                        	?>
                         <tr>
                        	<td></td>
					        <td></td>
					        <td><b style="color:#1788f4;"><i>Sub Total</i></b></td>
					        <td><b style="color:#1788f4;"><i><?php echo $totalqtybarang; $totalqtybarang=0;?></i></b></td>
					        <td><b style="color:#1788f4;"><i><?php echo $totalkubikasiseluruhnya; $totalkubikasiseluruhnya = 0;?></i></b></td>
                        </tr> 	
                        <?php 
                        }?>
                        
                      <?php
                    }
                  ?>
      </tbody>
      <tfoot>
        <tr>
	        <td></td>
	        <td></td>
	        <td><b style="color:#ff4646"><i>Total</i></b></td>
	        <td><b style="color:#ff4646"><i><?php $qty=0; foreach($tableprint as $d=>$data){$qty+=$data->qty_barang; } echo $qty; ?></i></b></td>
	        <td><b style="color:#ff4646"><i><?php $kubikasi=0; foreach($tableprint as $d=>$data){$kubikasi+=$data->total_kubikasi; } echo $kubikasi; ?></i></b></td>
        </tr>
      </tfoot>
    </table>
  </div>
<!-- halaman -->
  <div id="footer">
    <p class="page">Page</p>
  </div>
<!-- next page -->
  <div class="page_break"></div>
<!-- content page baru -->
  <div>
      <center><h4>KETERANGAN DRIVER</h4></center> <br>
      <div>

      <p>
        <?php 
        foreach ($tableprint as $key => $value) {
          echo $value->keterangan_driver;
          break;
        }
         ?>
      </p>
      </div>
  </div>
  <!-- halaman -->
  <div id="footer">
    <p class="page">Page</p>
  </div>
<!-- next page -->
  <div class="page_break"></div>
  <div>
     <center><h4>KETERANGAN OFFICE</h4></center>
     <div>
       <p><?php 
        foreach ($tableprint as $key => $value) {
          echo $value->keterangan_office;
          break;
        }
         ?></p>
     </div>
  </div>
  <div id="footer">
    <p class="page">Page</p>
  </div>
</body>
</html>

resources/views/registernew.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Teru Tritunggal | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{{asset('plugins/iCheck/all.css')}}">
    <!-- select2 -->
  <link rel="stylesheet" href="{{asset('bower_components/select2/dist/css/select2.min.css')}}"> 
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{asset('dist/css/skins/_all-skins.min.css')}}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a><b>Teru</b>Tritunggal</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Register a new membership</p>

    <form action="{{route('register')}}" method="post">
      @csrf

      <div class="form-group has-feedback">
         <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus placeholder ="Name">
         <span class="glyphicon glyphicon-user form-control-feedback"></span>
        @error('name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>

      <div class="form-group has-feedback">
         <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" placeholder ="E-Mail">
         <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>

       <div class="form-group has-feedback">
          <select class="form-control select2" data-placeholder="Jabatan" name="jabatan" style="width: 100%;" required>
            <?php 
              for ($i=0; $i<count($jabatan); $i++)
              { 
                $jab = $jabatan[$i];
                ?>
                  <option value="{{$jab->idjabatan}}" >
                    <?php 
                      echo $jab->nama_jabatan;
                     ?>
                  </option>
                <?php 
              }
             ?>
          </select>
      </div>
       @error('jabatan')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror

      <div class="form-group has-feedback">
          <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password" placeholder ="Password">
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        @error('password')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>


      <div class="form-group has-feedback">
          <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password" placeholder ="Re-type Password">  
          <span class="glyphicon glyphicon-log-in form-control-feedback"></span>        
      </div>

      <div class="row">
        <div class="col-xs-8">
        <!--   <div class="checkbox icheck">
            <label>
              <input type="checkbox"> I agree to the <a href="#">terms</a>
            </label>
          </div> -->
          <a href="{{route('login.loginnew')}}" class="text-center">I already have a membership</a>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  <!--   <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using
        Google+</a>
    </div> -->

    
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="{{asset('bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- iCheck -->
<script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
<script type="text/javascript">
   $('.select2').select2()
</script>
</body>
</html>